// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'https://localhost:44370' | (string & {});
};

export type CspApiDefinition = {
	id: string;
	enabled: boolean;
	reportOnly: boolean;
	isBackOffice: boolean;
	reportingDirective?: string | null;
	reportUri?: string | null;
	upgradeInsecureRequests: boolean;
	sources: Array<CspApiDefinitionSource>;
};

export type CspApiDefinitionSource = {
	definitionId: string;
	source: string;
	directives: Array<string>;
};

export type CspApiScriptItem = {
	id: string;
	src: string;
	description?: string | null;
	hash?: string | null;
	synchroniseOnStartup: boolean;
	lastUpdated?: string | null;
};

export type ProblemDetails = {
	type?: string | null;
	title?: string | null;
	status?: number | null;
	detail?: string | null;
	instance?: string | null;
	[key: string]: unknown;
};

export type GetUmbracoCspApiV1DefinitionsData = {
	body?: never;
	path?: never;
	query?: {
		isBackOffice?: boolean;
	};
	url: '/umbraco/csp/api/v1/Definitions';
};

export type GetUmbracoCspApiV1DefinitionsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetUmbracoCspApiV1DefinitionsResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type GetUmbracoCspApiV1DefinitionsResponse =
	GetUmbracoCspApiV1DefinitionsResponses[keyof GetUmbracoCspApiV1DefinitionsResponses];

export type PostUmbracoCspApiV1DefinitionsSaveData = {
	body?: CspApiDefinition;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Definitions/save';
};

export type PostUmbracoCspApiV1DefinitionsSaveErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type PostUmbracoCspApiV1DefinitionsSaveError =
	PostUmbracoCspApiV1DefinitionsSaveErrors[keyof PostUmbracoCspApiV1DefinitionsSaveErrors];

export type PostUmbracoCspApiV1DefinitionsSaveResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type PostUmbracoCspApiV1DefinitionsSaveResponse =
	PostUmbracoCspApiV1DefinitionsSaveResponses[keyof PostUmbracoCspApiV1DefinitionsSaveResponses];

export type GetUmbracoCspApiV1DirectivesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Directives';
};

export type GetUmbracoCspApiV1DirectivesErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetUmbracoCspApiV1DirectivesResponses = {
	/**
	 * OK
	 */
	200: Array<string>;
};

export type GetUmbracoCspApiV1DirectivesResponse =
	GetUmbracoCspApiV1DirectivesResponses[keyof GetUmbracoCspApiV1DirectivesResponses];

export type GetUmbracoCspApiV1ScriptItemsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/ScriptItems';
};

export type GetUmbracoCspApiV1ScriptItemsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetUmbracoCspApiV1ScriptItemsResponses = {
	/**
	 * OK
	 */
	200: Array<CspApiScriptItem>;
};

export type GetUmbracoCspApiV1ScriptItemsResponse =
	GetUmbracoCspApiV1ScriptItemsResponses[keyof GetUmbracoCspApiV1ScriptItemsResponses];

export type DeleteUmbracoCspApiV1ScriptItemsByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/csp/api/v1/ScriptItems/{id}';
};

export type DeleteUmbracoCspApiV1ScriptItemsByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type DeleteUmbracoCspApiV1ScriptItemsByIdResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type GetUmbracoCspApiV1ScriptItemsByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/csp/api/v1/ScriptItems/{id}';
};

export type GetUmbracoCspApiV1ScriptItemsByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetUmbracoCspApiV1ScriptItemsByIdResponses = {
	/**
	 * OK
	 */
	200: CspApiScriptItem;
};

export type GetUmbracoCspApiV1ScriptItemsByIdResponse =
	GetUmbracoCspApiV1ScriptItemsByIdResponses[keyof GetUmbracoCspApiV1ScriptItemsByIdResponses];

export type PostUmbracoCspApiV1ScriptItemsByIdRegenerateHashData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/csp/api/v1/ScriptItems/{id}/regenerate-hash';
};

export type PostUmbracoCspApiV1ScriptItemsByIdRegenerateHashErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type PostUmbracoCspApiV1ScriptItemsByIdRegenerateHashResponses = {
	/**
	 * OK
	 */
	200: CspApiScriptItem;
};

export type PostUmbracoCspApiV1ScriptItemsByIdRegenerateHashResponse =
	PostUmbracoCspApiV1ScriptItemsByIdRegenerateHashResponses[keyof PostUmbracoCspApiV1ScriptItemsByIdRegenerateHashResponses];

export type PostUmbracoCspApiV1ScriptItemsSaveData = {
	body?: CspApiScriptItem;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/ScriptItems/save';
};

export type PostUmbracoCspApiV1ScriptItemsSaveErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type PostUmbracoCspApiV1ScriptItemsSaveError =
	PostUmbracoCspApiV1ScriptItemsSaveErrors[keyof PostUmbracoCspApiV1ScriptItemsSaveErrors];

export type PostUmbracoCspApiV1ScriptItemsSaveResponses = {
	/**
	 * OK
	 */
	200: CspApiScriptItem;
};

export type PostUmbracoCspApiV1ScriptItemsSaveResponse =
	PostUmbracoCspApiV1ScriptItemsSaveResponses[keyof PostUmbracoCspApiV1ScriptItemsSaveResponses];
